In [1]:
import os
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Set the path to the directory containing your test images
test_dir = r'C:\Users\Abhinav Vannoj\Downloads\MajorProject-main\MajorProject-main\Data\Emotion_dataset\validation'

# Set the image size based on your model's input size
IMAGE_SIZE = (48, 48)

# Create an ImageDataGenerator for test data
test_datagen = ImageDataGenerator(rescale=1./255)

# Create a test dataset
test_dataset = test_datagen.flow_from_directory(
    directory=test_dir,
    target_size=IMAGE_SIZE,
    class_mode='categorical',
    shuffle=False,  # Set to False to maintain the order of predictions
    batch_size=64  # Adjust based on your system's memory
)

# Load the saved model
with open("model.json", "r") as json_file:
    loaded_model_json = json_file.read()
    model = tf.keras.models.model_from_json(loaded_model_json)

# Load the model weights
model.load_weights("model_final.h5")

# Compile the model
model.compile(optimizer='adam',  # Add your optimizer
              loss='categorical_crossentropy',  # Add your loss function
              metrics=['accuracy'])  # Add your metrics

# Evaluate the model on the test dataset
# Evaluate the model on the test dataset
test_evaluation = model.evaluate(test_dataset, steps=70)  # Adjust the number of steps as needed


# Get predictions on the test dataset
predictions = model.predict(test_dataset)

# Convert predictions to class labels
predicted_classes = np.argmax(predictions, axis=1)

# Get true labels
true_labels = test_dataset.classes

# Calculate confusion matrix
confusion_matrix = tf.math.confusion_matrix(
    true_labels,
    predicted_classes,
    num_classes=len(test_dataset.class_indices)
)

# Print the evaluation metrics
print("Test Loss:", test_evaluation[0])
print("Test Accuracy:", test_evaluation[1])

# Print or use the confusion matrix as needed
print("Confusion Matrix:")
print(confusion_matrix)



Found 7066 images belonging to 7 classes.





111/111 [==============================] - 54s 481ms/step
Test Loss: 0.9420068860054016
Test Accuracy: 0.7261160612106323
Confusion Matrix:
tf.Tensor(
[[ 647   25   28   59  144   45   12]
 [  10   98    1    1    1    0    0]
 [ 149   16  423   45  148  148   89]
 [  31    3   18 1637   80   14   42]
 [  76    5   23  121  921   50   20]
 [ 133   20   68   85  301  523    9]
 [  19    3   36   29   33   10  667]], shape=(7, 7), dtype=int32)
